[Khải Thư] Get Movies
vuphu-jc/3CTech-android-final-project pull request #3
Opened 2021-04-09 09:16 UTC by dangcongkhaithu

2021-04-09 09:52 UTC, chuongdevJC requested changes

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/MainActivity.kt
> +        //var result:Result = Result(true, "a", arrayListOf(1,2,3),1)
remove

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/MainActivity.kt
> +    private var navSelectedListener: BottomNavigationView.OnNavigationItemSelectedListener =
using implement for override

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +
remove blank line

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +class HomePageRecyclerAdapter(var lists: MutableList<ResultMovie>) :
```suggestion
class HomePageRecyclerAdapter(var lists: List<ResultMovie>) :
```

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +        var imageMovie: ImageView = itemView.findViewById(R.id.imageMovie)
if we have just one view holder. try to use import kotlin extension

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/SliderAdapter.kt
> +class SliderAdapter(var context: Context, var sliderItems: MutableList<SliderData>) :
```suggestion
class SliderAdapter(var context: Context, var sliderItems: List<SliderData>) :
```

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/SliderAdapter.kt
> +        }
move to viewholder

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/api/RestClient.kt
> +
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/model/PageMovie.kt
> +
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/model/ResultMovie.kt
> +    var genreIds: MutableList<Int>,
```suggestion
    var genreIds: List<Int>,
```

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/model/UrlApi.kt
> +    var apiKey: String ,
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/model/enum/LanguageEnum.kt
> +        return s
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/presenter/GetMoviePresenter.kt
> +class GetMoviePresenter(var iHomePageFragment: IHomePageFragment) : IGetMoviePresenter {
```suggestion
class GetMoviePresenter(val iHomePageFragment: IHomePageFragment) : IGetMoviePresenter {
```

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/presenter/GetMoviePresenter.kt
> +                println()
remove if not use

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/presenter/interfacePre/IGetMoviePresenter.kt
> +
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/view/fragment/HomePageFragment.kt
> +
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/view/fragment/HomePageFragment.kt
> +    @SuppressLint("WrongConstant")
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/view/fragment/HomePageFragment.kt
> +        //createRecyclerView(view)
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/view/fragment/HomePageFragment.kt
> +        sliderAdapter = context?.let { SliderAdapter(it, sliderItems) }!!
remove !!

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/view/fragment/HomePageFragment.kt
> +
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/view/interfaceView/IHomePageFragment.kt
> +    fun onMoviesReceived(movies:  MutableList<ResultMovie>, view: View)
```suggestion
    fun onMoviesReceived(movies:  List<ResultMovie>, view: View)
```

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/activity_main.xml
> +        android:background="#032541"
using color res

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="60sp"
using dimension

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/activity_main.xml
> +        app:title="TMDb Fake"
using value string

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/activity_main.xml
> +        android:background="#032541"
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/fragment_homepage.xml
> +                android:layout_height="200dp"
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/fragment_homepage.xml
> +                android:layout_margin="20dp"
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/fragment_homepage.xml
> +                android:textSize="20sp" />
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/item_movie.xml
> +    android:layout_margin="5dp"
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/item_movie.xml
> +    app:cardCornerRadius="5dp">
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/item_movie.xml
> +        android:paddingBottom="10dp">
.

2021-04-09 09:52 UTC, chuongdevJC commented on app/src/main/res/layout/item_movie.xml
> +            android:text="Day ngay gio"
.

2021-04-09 09:54 UTC, vuphu-jc commented on app/src/main/res/layout/fragment_homepage.xml
> +                android:text="What's Popular"
You should define text (`What's Popular`) in `strings.xml`

2021-04-09 09:54 UTC, vuphu-jc commented on app/src/main/res/layout/activity_main.xml
> +        android:background="#032541"
You should define hex color (#032541) in `colors.xml`

2021-04-09 09:54 UTC, vuphu-jc commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/api/RestClient.kt
> +
remove blank lines (line `12`, `13`)

2021-04-09 09:54 UTC, vuphu-jc commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/presenter/interfacePre/IGetMoviePresenter.kt
> +}
Name of presenter should same as name of view. 
Example: `HomePresenter`, `HomeFragment`

2021-04-09 09:54 UTC, vuphu-jc commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/presenter/GetMoviePresenter.kt
> +    lateinit var litOfMovies: MutableList<ResultMovie>
We don't need define variable `litOfMovies`.

2021-04-09 09:54 UTC, vuphu-jc commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/presenter/GetMoviePresenter.kt
> +            }
You should define method `onError()` at `View`
```suggestion
            override fun onFailure(call: Call<PageMovie>, t: Throwable) {
                view?.onError(< message or anything you want>)
            }
```

2021-04-13 07:27 UTC, vuphu-jc approved these changes

2021-04-13 07:27 UTC, vuphu-jc commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +        Glide.with(holder.view).load("https://image.tmdb.org/t/p/w500/${movie.posterPath}")
define `https://image.tmdb.org/t/p/w500/` at Constants

2021-04-13 07:27 UTC, vuphu-jc commented on app/src/main/res/values/colors.xml
>  </resources>
add endline

2021-04-13 07:27 UTC, vuphu-jc commented on app/src/main/res/values/dimension.xml
> +</resources>
add endline

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/MainActivity.kt
> +    override fun onNavigationItemSelected(item: MenuItem): Boolean {
.

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +        var view: View = inflater.inflate(R.layout.item_movie, parent, false)
val

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +        var context: Context = parent.context
remove

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +        var inflater: LayoutInflater = LayoutInflater.from(context)
val

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +        var movie: ResultMovie = lists[position]
val

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +        Glide.with(holder.view).load("https://image.tmdb.org/t/p/w500/${movie.posterPath}")
move all this logic into viewholder

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +        var view: View = itemView
.

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/HomePageRecyclerAdapter.kt
> +        }
remove

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/adapter/SliderAdapter.kt
> +        Glide.with(viewHolder.view).load(sliderData.urlImage).into(viewHolder.imageView)
viewHolder.bind(sliderItems[position])

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/api/RestClient.kt
> +    }
create func get retrofit create()

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/model/enum/LanguageEnum.kt
> +
.

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/presenter/GetMoviePresenter.kt
> +        retrofit = RestClient.getInstanceRetrofit(urlApi.baseUrl)!!
avoid force wrap '!!'

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/model/UrlApi.kt
> +class UrlApi(
change name to MovieRequest

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/presenter/GetMoviePresenter.kt
> +        "popular"
avoid hard code

2021-04-13 08:20 UTC, chuongdevJC commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/view/fragment/HomeView.kt
> +        view.slider.startAutoCycle()
view.slider.apply{ 
// ur logic
}

2021-04-13 08:37 UTC, AnhJobChat commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/view/fragment/HomeView.kt
> +    }
no need to pass view over classes. Just create a variable is mView, then set it = view in onCreateView. then you can use mView to create recyclerview

2021-04-16 02:52 UTC, AnhJobChat commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/view/fragment/HomeView.kt
> +        createRecyclerView(mView)
should setup recyclerview in onCreateView, onMoviesReceived just update data by adapter

2021-04-16 02:52 UTC, AnhJobChat commented on app/src/main/java/com/khaithu/a3ctech_android_final_project/model/MovieRequest.kt
> +class MovieRequest(
use data class

2021-04-16 02:56 UTC, chuongdevJC approved these changes

2021-04-16 02:56 UTC, chuongdevJC commented on app/src/main/res/values/dimension.xml
> +</resources>
.

2021-04-16 02:56 UTC, chuongdevJC commented on app/src/main/res/values/colors.xml
>  </resources>
.

2021-04-16 03:45 UTC, AnhJobChat approved these changes

2021-04-16 03:46 UTC, merged